/* Database schema to keep the structure of entire database. */

CREATE DATABASE vet_clinic
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;



CREATE TABLE animals (
id INT GENERATED BY DEFAULT AS IDENTITY,
	name varchar(100) NULL,
	date_of_birth date NULL,
	escape_attempts INT NULL,
	neutered boolean NULL,
	weight_kg decimal,
	PRIMARY KEY (id)
);
